# Generated by Django 4.1.10 on 2024-01-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile_friendship"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(fields=("follower", "followee"), name="unique_following_followee"),
        ),
    ]
