# Generated by Django 4.1.10 on 2024-02-02 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweets", "0003_alter_tweet_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "likedtweet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="likedtweet", to="tweets.tweet"
                    ),
                ),
                (
                    "likeuser",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(fields=("likeuser", "likedtweet"), name="unique_like"),
        ),
    ]
